### ISSUE TITLE
Contribute HotCodeReloader upstream?

### ISSUE THREAD

**Issue by weierophinney** [samuelnogueira/zend-expressive-swoole#1]
Hi, @samuelnogueira !

An Expressive user on the ZF slack pointed me to this:

- https://github.com/samuelnogueira/zend-expressive-swoole/blob/master/src/Tick/HotCodeReloader.php

I'm curious:

- when/where do you register this?
- would you be interested in contributing it upstream?

I recently gave a talk at DayCamp4Developers about the Expressive/Swoole bindings, and I noted at the time that development against Swoole is problematic in part due to the need to reload the server for any code changes. Being able to mitigate that during development would solve that aspect, so I'm quite interested in this approach.

Many thanks in advance!

**Comment by samuelnogueira** [comment]
Hi @weierophinney !

> when/where do you register this?

The "check-for-changes" periodic method call is registered on each server worker, on it's `'WorkerStart'` event (see https://github.com/samuelnogueira/zend-expressive-swoole/blob/master/src/Http/Factory/SwooleHttpServerFactory.php#L45)

> would you be interested in contributing it upstream?

I'll be happy to!
There are a few caveats with this approach though:
1. Requires `inotify` extension
2. It reloads the swoole workers instead of re-bootstrapping the entire application. This means all .php files which were loaded when the Swoole Server was first started will not be reloaded (e.g. for expressive apps: config/config.php, config/routes.php, all config providers, some factories). See https://www.swoole.co.uk/docs/modules/swoole-server-methods#public-boolean-swoole-server-reload-void for details.

I can provide a PR for zendframework/zend-expressive-swoole with this feature, so changes/improvements in the approach can be placed there.

Thank you for reaching out!

**Comment by weierophinney** [comment]
Those sound reasonable. We can detail that the `inotify` extension is required to do hotloading (and list it as a suggested dependency in the package), and document the limitations (e.g., "it will not pick up added routes or pipeline middleware, nor changes to the server or Application instances").

Looking forward to the patch!

**Comment by samuelnogueira** [comment]
Pull request added to zend framework repository: https://github.com/zendframework/zend-expressive-swoole/pull/60
